/*
 * <one line to give the library's name and an idea of what it does.>
 * Copyright (C) 2015  <copyright holder> <email>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

#include <tuxls/utf/Icons.h>

namespace tux
{
Icon::DataArray Icon::Data =
{
    COk                ,
    CComment           ,
    CArrowRight        ,
    CArrowLeft         ,
    CArrowUp           ,
    CArrowDown         ,
    CArrowUpRight      ,
    CArrowUpLeft       ,
    CArrowDownRight    ,
    CArrowDownLeft     ,
    CArrowHeadRight    ,
    CArrowDheadRight   ,
    CPencilDr          ,
    CPencilUr          ,
    CErr1              ,
    CFlag              ,
    CBolt              ,
    CSuccess           ,
    CSmallDot          ,
    CBigDot            ,
    CBall1             ,
    CBall2             ,
    CDeadHead          ,
    CYinYang           ,
    CSadface           ,
    CHappy1            ,
    CHappy2            ,
    CCircleX           ,
    CFunction          ,
    CCut1              ,
    CCut2              ,
    CCut3              ,
    CCMarkX            ,
    CBaseline          ,
    CStar5             ,
    CCMarkCheck        ,
    CSwordCross        ,
    CHammerCross       ,
    CSmallDot2         ,
    CErr2              ,
    CErr3              ,
    CSQuote1           ,
    CDQuoteLeft        ,
    CDuoteRight        ,
    CDowntobottomleft  ,
    CUndo              ,
    CEnter             ,
    CKeyEnter          ,
    CLinux             ,
    CArch              ,
    CHome              ,
    CFile              ,
    CThumbDown         ,
    CGithubCircle      ,
    CGithubFolder      ,
    CWindows           ,
    CPi                ,
    CFolder            ,
    CBug               ,
    CInfo              ,
    CWarning           ,
    CBomb              ,
    CEditPencilBR      ,
    CEditPencilR       ,
    CEditPencilUR      ,
    CNegCrossCheck     ,
    CShadowedCheckBox  ,
    CSpinArrowSpin0    ,
    CSpinArrowSpin1    ,
    CSpinArrowSpin2    ,
    CSpinArrowSpin3    ,
    CSpinArrowSpin4    ,
    CSpinArrowSpin5    ,
    CSpinArrowSpin6    ,
    CSpinArrowSpin7    ,
    CThumbUp           ,
    CChronos           ,
    CSand              ,
    CCoffee            ,
    CUnAuth            ,
    CHandwrite         ,
    CWorld             ,
    CWorldGrid         ,
    CSchool            ,
    CHat               ,
    CAdmin             ,
    CFabric            ,
    CCat               ,
    CFish              ,
    CSearch            ,
    CPeople            ,
    CAlien             ,
    CLight             ,
    CPoop              ,
    CCash              ,
    CComputer          ,
    CNotePad           ,
    CBooks             ,
    CSend              ,
    CRecieve           ,
    CEmail             ,
    CEmail2

};
const char* IcNames[] =
{
    "Ok",
    "Comment",
    "ArrowRight",
    "ArrowLeft",
    "ArrowUp",
    "ArrowDown",
    "ArrowUpRight",
    "ArrowUpLeft",
    "ArrowDownRight",
    "ArrowDownLeft",
    "ArrowHeadRight",
    "ArrowDheadRight",
    "PencilDr",
    "PencilUr",
    "Err1",
    "Flag",
    "Bolt",
    "Success ",
    "SmallDot",
    "BigDot",
    "Ball1",
    "Ball2",
    "DeadHead",
    "YinYang",
    "Sadface",
    "Happy1",
    "Happy2",
    "CircleX",
    "Function",
    "Cut1",
    "Cut2",
    "Cut3",
    "CMarkX",
    "Baseline",
    "Star5",
    "CMarkCheck",
    "SwordCross",
    "HammerCross",
    "SmallDot2",
    "Err2",
    "Err3",
    "SQuote1",
    "DQuoteLeft",
    "DuoteRight",
    "Downtobottomleft",
    "Undo",
    "Enter",
    "KeyEnter",
    "Linux",
    "Arch",
    "Home",
    "File",
    "ThumbDown ",
    "GithubCircle",
    "GithubFolder",
    "Windows",
    "Pi",
    "Folder",
    "Bug",
    "Info",
    "Warning",
    "Bomb",
    "EditPencilBR",
    "EditPencilR",
    "EditPencilUR",
    "NegCrossCheck",
    "ShadowedCheckBox",
    "SpinArrowSpin0",
    "SpinArrowSpin1",
    "SpinArrowSpin2",
    "SpinArrowSpin3",
    "SpinArrowSpin4",
    "SpinArrowSpin5",
    "SpinArrowSpin6",
    "SpinArrowSpin7",
    "ThumbUp",
    "Chronos",
    "Sand",
    "Coffee",
    "UnAuth",
    "Handwrite",
    "World",
    "WorldGrid",
    "School",
    "Hat",
    "Admin",
    "Fabric",
    "Cat",
    "Fish",
    "Search",
    "People",
    "Alien",
    "Light",
    "Poop",
    "Cash",
    "Computer",
    "NotePad",
    "Books",
    "Send",
    "Recieve",
    "Email",
    "Email2"
};

Icon::Type Icon::Scan(std::string IcName)
{
    int N = 0;
    for (auto Str : IcNames)
    {
        if (IcName == Str) return N;
        ++N;
    }
    return 0;
}

}
